services:
  web:
    image: codingmitschl/exhibitions:latest
    build: .
    volumes:
      - .:/app
  web-migrate:
    extends:
      service: web
    command: python manage.py migrate
  web-collectstatic:
    extends:
      service: web
    command: python manage.py collectstatic --noinput
  web-run:
    extends:
      service: web
    command: gunicorn django_test.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - SECRET_KEY=secret
      - ALLOWED_HOSTS=0.0.0.0,localhost