services:
  web:
    image: codingmitschl/exhibitions:latest
    build: .
    volumes:
      - .:/app
  web-migrate:
    extends:
      service: web
    command: python manage.py migrate
  web-run:
    extends:
      service: web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"