# Generated by Django 5.0.7 on 2024-07-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exhibition",
            name="description_image",
            field=models.ImageField(default=None, null=True, upload_to="images/"),
        ),
    ]
