# Generated by Django 5.0.7 on 2024-07-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objects", "0002_exhibition_description_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="exhibition",
            name="description_headline",
            field=models.CharField(default="Test", max_length=100),
            preserve_default=False,
        ),
    ]
