# Generated by Django 5.0.7 on 2024-07-28 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objects", "0003_exhibition_description_headline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objectdetailsection",
            name="object_detail_page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="objects.object"
            ),
        ),
        migrations.AddField(
            model_name="object",
            name="banner_image",
            field=models.ImageField(default=None, null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="object",
            name="subline",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="ObjectDetailPage",
        ),
    ]
